# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-01 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeHealedAPI', '0004_pedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedia',
            name='reply_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedia',
            name='reply_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedia',
            name='reply_yes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedia',
            name='score',
            field=models.IntegerField(default=100),
        ),
    ]
