# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-01 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeHealedAPI', '0006_auto_20180901_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedia',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
