# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-03 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeHealedAPI', '0009_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_sentence', models.CharField(max_length=2000)),
                ('translated_sentence', models.CharField(max_length=2000)),
                ('size', models.IntegerField(default=0)),
            ],
        ),
    ]
