# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-06 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeHealedAPI', '0011_medicalrecordimagedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='code',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='pedia',
            name='dictionary',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='WeHealedAPI.Dictionary'),
        ),
    ]
