# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-06 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeHealedAPI', '0012_auto_20180906_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedia',
            name='dictionary',
            field=models.IntegerField(default=0),
        ),
    ]
