# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-06 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeHealedAPI', '0013_auto_20180906_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlittoCallbackDB',
            fields=[
                ('src_lang_code', models.CharField(max_length=10)),
                ('dst_lang_code', models.CharField(max_length=10)),
                ('cp_transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('translation', models.CharField(max_length=5000)),
                ('callback_url', models.CharField(max_length=200)),
                ('cp_content_id', models.CharField(max_length=200)),
                ('confirm_url', models.CharField(max_length=200)),
                ('callback_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
