# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-08 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeHealedAPI', '0014_flittocallbackdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedia',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
